// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsrUDn1NXEP4e9WOj8WIuDMOQJYPwmx0M',
    appId: '1:1084998872893:web:02e360bebdb2abbf615f54',
    messagingSenderId: '1084998872893',
    projectId: 'ventaia-prod',
    authDomain: 'ventaia-prod.firebaseapp.com',
    storageBucket: 'ventaia-prod.firebasestorage.app',
    measurementId: 'G-NEVR0MBDLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg9z8OeXyRAlEycsEBKCQNJXwBVG_JWGE',
    appId: '1:1084998872893:android:4a62c013373ceafa615f54',
    messagingSenderId: '1084998872893',
    projectId: 'ventaia-prod',
    storageBucket: 'ventaia-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5FUb8XoFvzQAWb5QKGf5ik_HjBM-8nnw',
    appId: '1:1084998872893:ios:81475a87b0cafdd1615f54',
    messagingSenderId: '1084998872893',
    projectId: 'ventaia-prod',
    storageBucket: 'ventaia-prod.firebasestorage.app',
    iosClientId: '1084998872893-87s6j2nh6iimqmsari36i4rokl6pstig.apps.googleusercontent.com',
    iosBundleId: 'com.salesai.salesAiSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5FUb8XoFvzQAWb5QKGf5ik_HjBM-8nnw',
    appId: '1:1084998872893:ios:81475a87b0cafdd1615f54',
    messagingSenderId: '1084998872893',
    projectId: 'ventaia-prod',
    storageBucket: 'ventaia-prod.firebasestorage.app',
    iosClientId: '1084998872893-87s6j2nh6iimqmsari36i4rokl6pstig.apps.googleusercontent.com',
    iosBundleId: 'com.salesai.salesAiSeller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsrUDn1NXEP4e9WOj8WIuDMOQJYPwmx0M',
    appId: '1:1084998872893:web:e3b51263cbee7ada615f54',
    messagingSenderId: '1084998872893',
    projectId: 'ventaia-prod',
    authDomain: 'ventaia-prod.firebaseapp.com',
    storageBucket: 'ventaia-prod.firebasestorage.app',
    measurementId: 'G-2QCPXX38W0',
  );
}
